on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: env | sort

    - name: Install React
      run: npm install react react-dom prop-types
    - run: npm install
    - name: Install example
      run: cd ./example && npm install && cd ..

    - run: npm run build
    - name: Run Cypress tests
      run: |
        npm run build &
        cd ./example && npm run start:silent &
        npm run cypress:run -- --record --key ${{ secrets.CYPRESS_KEY }}
